services:
  umbrel:
    image: tao9317/tao-umbrel:1.5.0

    container_name: umbrel
    pid: host
    ports:
      - "80:80"
    volumes:
      - ./umbrel:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    stop_grace_period: 1m
